MODEL:
#  TYPE: swin
#  TYPE: RelaHash
#  TYPE: navigateNet
#  TYPE: FAH
  TYPE: Network
  NAME: hash_finetune
  DROP_PATH_RATE: 0.2  # origin 0.5
  NUM_CLASSES: 21
  hash_length: 16
  alph_param: 20
  beta_param: 200
  margin: 10
#  swin:
#    EMBED_DIM: 96
#    DEPTHS: [ 2, 2, 6, 2 ]
#    NUM_HEADS: [ 3, 6, 12, 24 ]
#    WINDOW_SIZE: 7
  Network:
    EMBED_DIM: 384
    DEPTHS: 12
    NUM_HEADS: 12
    WINDOW_SIZE: 7
#  FAH:
#    EMBED_DIM: 384
#    DEPTHS: 12
#    NUM_HEADS: 12
#    WINDOW_SIZE: 7
#  NavigateNet:
#    EMBED_DIM: 384
#    DEPTHS: 12
#    NUM_HEADS: 12
#    WINDOW_SIZE: 7
#TRAIN:
#  EPOCHS: 50
#  WARMUP_EPOCHS: 5
#  WEIGHT_DECAY: 0.0005
#  BASE_LR: 0.0001
#  WARMUP_LR: 2e-08
#  MIN_LR: 2e-07
#  TRIPLET_STRATEGY: batch_corrective
#TRAIN:
#  EPOCHS: 50
#  WARMUP_EPOCHS: 5
#  WEIGHT_DECAY: 0.0004
#  BASE_LR: 6.25e-07
#  WARMUP_LR: 0.00001
#  MIN_LR: 6.25e-08
#  TRIPLET_STRATEGY: batch_corrective

#dg
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.0004
  BASE_LR: 0.0001
  WARMUP_LR: 0.00001
  MIN_LR: 0.000001
  TRIPLET_STRATEGY: batch_corrective



#TRAIN:
#  EPOCHS: 50
#  WARMUP_EPOCHS: 5
#  WEIGHT_DECAY: 0.0001
#  BASE_LR: 0.001
#  WARMUP_LR: 0.00001
#  MIN_LR: 0.000001
#  TRIPLET_STRATEGY: batch_corrective

#FAH
#TRAIN:
#  EPOCHS: 80
#  WARMUP_EPOCHS: 5
#  WEIGHT_DECAY: 0.0005
#  BASE_LR: 1e-4
#  WARMUP_LR: 0.00001
#  MIN_LR: 0.000001
#  TRIPLET_STRATEGY: batch_corrective

DATA:
  NUM_WORKERS: 8
  DATASET: UCMD
